apiVersion: v1
kind: Service
metadata:
  namespace: {{ namespace }}
  name: kibana
  labels:
    app: kibana
spec:
  selector:
    app: kibana
  ports:
    - port: 5601
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ namespace }}
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      nodeSelector:
        nodetype: test    
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.1.1
          ports:
            - containerPort: 5601
          env:
            - name: SERVER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SERVER_HOST
              value: "0.0.0.0"
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch.{{ namespace }}.svc.cluster.local:9200

