---        
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana
  namespace: {{ namespace }}
spec:
  rules:
  - host: kibana-testelk.apps.xbrain.local
    http:
      paths:
      - path: /
        backend:
          serviceName: kibana
          servicePort: http