apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ namespace }}
  name: logstash-config
data:
  logstash.conf: |
    input {
        beats {
            port => 5044
        }
    }

    output {
          elasticsearch {
              hosts => ["http://elasticsearch.{{ namespace }}.svc.cluster.local:9200"]
              manage_template => false
          }
    }