
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ namespace }}
  name: logstash
  labels:
    app: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      nodeSelector:
        nodetype: test    

      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:7.1.1
          ports:
            - containerPort: 5044
          volumeMounts:
            - name: logstash-config
              mountPath: /usr/share/logstash/pipeline
          env:
            - name: logstash.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      volumes:
        - name: logstash-config
          configMap:
            name: logstash-config
